spring:
  application:
    name: payments-service
  datasource:
    url: jdbc:postgresql://localhost:5423/payments_pedidos_db
    username: payments_pedidos
    password: user123
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payments-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.codigo.pedido.payments.infrastructure.messaging.event"
        spring.json.value.default.type: com.codigo.pedido.payments.infrastructure.messaging.event.PedidoCreadoEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

server:
  port: 8085

events:
  topics:
    pedido-creado: pedido-creado
    pago-aprobado: pago-aprobado
    pago-rechazado: pago-rechazado

resilience:
  kafka:
    max-retries: 3
    retry-interval-ms: 2000
