apiVersion: v1
kind: Secret
metadata:
  name: usuarios-app-secret
type: Opaque
stringData:
  DB_USERNAME: usuarios_pedidos
  DB_PASSWORD: user123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuarios
spec:
  replicas: 2
  selector:
    matchLabels:
      app: usuarios
  template:
    metadata:
      labels:
        app: usuarios
    spec:
      containers:
        - name: usuarios
          image: usuarios:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: DB_URL
              value: jdbc:postgresql://postgres-usuarios:5432/usuarios_pedidos_db
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: usuarios-app-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: usuarios-app-secret
                  key: DB_PASSWORD
            - name: LOG_LEVEL
              value: INFO
            - name: DDL_AUTO
              value: update
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 40
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: usuarios
spec:
  selector:
    app: usuarios
  ports:
    - name: http
      port: 8082
      targetPort: 8082
